"""
reporter/markdown.py

Renders a full Markdown modernisation report from analysis results.
"""

from __future__ import annotations
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from parser.structure import CobolProgram
    from parser.antipatterns import Finding
    from parser.complexity import ComplexityScore

_SEVERITY_EMOJI = {'HIGH': '🔴', 'MEDIUM': '🟡', 'LOW': '🟢'}


def render(
    prog: "CobolProgram",
    findings: list["Finding"],
    scores: list["ComplexityScore"],
    source_path: str,
    annotations: dict[str, str] | None = None,
) -> str:
    lines: list[str] = []

    lines.append(f"# COBOL Modernisation Report")
    lines.append(f"\n**File:** `{source_path}`  ")
    lines.append(f"**Program ID:** `{prog.program_id}`  ")
    lines.append(f"**Total lines:** {len(prog.raw_lines)}  ")
    lines.append(f"**Data items:** {len(prog.data_items)}  ")
    lines.append(f"**Paragraphs:** {len(prog.paragraphs)}  ")

    # ── Summary ──────────────────────────────────────────────────────────────
    high   = sum(1 for f in findings if f.severity == 'HIGH')
    medium = sum(1 for f in findings if f.severity == 'MEDIUM')
    low    = sum(1 for f in findings if f.severity == 'LOW')

    lines.append("\n---\n")
    lines.append("## Summary\n")
    lines.append(f"| Severity | Count |")
    lines.append(f"|----------|-------|")
    lines.append(f"| 🔴 High   | {high} |")
    lines.append(f"| 🟡 Medium | {medium} |")
    lines.append(f"| 🟢 Low    | {low} |")

    # ── Anti-patterns ─────────────────────────────────────────────────────────
    lines.append("\n---\n")
    lines.append("## Anti-patterns Detected\n")
    if not findings:
        lines.append("✅ No anti-patterns detected.")
    else:
        for f in findings:
            emoji = _SEVERITY_EMOJI.get(f.severity, '')
            lines.append(f"### {emoji} `{f.category}` — Line {f.line}")
            lines.append(f"\n{f.description}\n")
            if f.snippet:
                lines.append(f"```cobol\n{f.snippet}\n```\n")

    # ── Complexity ────────────────────────────────────────────────────────────
    lines.append("\n---\n")
    lines.append("## Paragraph Complexity (Top 10)\n")
    lines.append("| Rank | Paragraph | Complexity | Line |")
    lines.append("|------|-----------|------------|------|")
    for i, s in enumerate(scores[:10], 1):
        flag = " ⚠️" if s.score >= 10 else ""
        lines.append(f"| {i} | `{s.paragraph}` | {s.score}{flag} | {s.line} |")

    # ── Data inventory ────────────────────────────────────────────────────────
    lines.append("\n---\n")
    lines.append("## Working-Storage Data Items\n")
    lines.append("| Level | Name | PIC | Value |")
    lines.append("|-------|------|-----|-------|")
    for d in prog.data_items:
        lines.append(f"| {d.level:02d} | `{d.name}` | `{d.pic or '-'}` | `{d.value or '-'}` |")

    # ── Paragraph annotations ─────────────────────────────────────────────────
    if annotations:
        lines.append("\n---\n")
        lines.append("## Paragraph Annotations\n")
        for para_name, summary in annotations.items():
            lines.append(f"### `{para_name}`\n")
            lines.append(f"{summary}\n")

    lines.append("\n---\n")
    lines.append("*Generated by [cobol-moderniser](https://github.com/Atri2-code/cobol-moderniser)*")

    return '\n'.join(lines)
